name: Build Installer
run-name: Build Installer for ${{ github.actor }}
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Clone the repo
        uses: actions/checkout@v4

      - name: Build the installer in Docker
        run: docker run --privileged -v $(pwd):/workdir ghcr.io/joeyeamigh/nixos-superbird/builder:latest

      - name: Change ownership of the out dir
        run: sudo chown -R $(whoami):$(whoami) ./out

      - name: Archive the installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.actor }}-nixos-superbird-installer
          path: ./out/*
